language: rust
rust:
- stable
os:
- osx

cache: cargo

before_script:
- rustup component add rustfmt

script:
- cargo build --release --verbose --all
- cargo test --release --verbose --all
- cargo fmt --all -- --check
- cargo doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: target/doc/succinct
  on:
    branch: master

branches:
  only:
  - master

env:
  global:
    secure: GYJ6E1DRXh5n8hclgElu/kQ3mavblgCdstrCEtt0WVC55pIOOlbgK8CUoLyD6YZ7azJonu9P9DhnvTSzxVwauX7J35kSoxyAmsvyHwVn4+mq06xZZJRMIj46lhX1ze0RvGEXCw7sG4UKtX2z/sUk/couf0J+L7mlDzRQdcGX3kEY3ci0Qm2cquX9M/ymDUGz1KOTcC8pDS91BKv4IXwy0pGGU/QE2zJt9czeWmAOMJcPTRa004iIqqHjyC6VOsnMGc4ss/LcmNAY0x5NCGUom17O5ovyGeqVm8JYK3tp+NU65Kut8k34MLaONdZxnp+bKRj5r6wHig+bxklraVR0BOK80IGI9gHB0brvHD6isYSjm+z7fvuV/XfSmkqsbZpqelgeuc2mHrG7NmYbtznxUfFoS/6Kb7rSA9av9W2/AXnHcT3ODbxn9NLPqEGM//Al+uy/job4cXYQRmJX4Cg7ROs+ch/9pGJDsNZ5E2h4eAc5HGGoLxDPE7Ip6neV3GslO6j9Lv1/hNQFN88HO//v6g02VxcRK043TPXIRl3q9CR88ucr3+MtzYyXlckefRmW7YKFElQ/3yYtwGrafdPkGQQy2Yuax8gcoNq41pkzHwC9ip/R1GEvof5MmqxgsBerbtOZkTA19/oRwboAYXH23fuA7DEAIRBG3ayA29t0SFo=
