language: rust
rust:
  # - 1.33.0  # pinned stable Rust release
  - stable
  # - beta
  # - nightly
os:
  - linux
  # - osx

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all
  - cargo fmt --all -- --check
  - cargo doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  # on:
  #   branch: master

branches:
  only:
    - master
