language: rust
rust:
  - 1.33.0  # pinned stable Rust release
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache: cargo

before_script:
  - rustup component add rustfmt

script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all
  - cargo fmt --all -- --check

branches:
  only:
    - master
