language: rust
rust:
  - 1.33.0  # pinned stable Rust release
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
